language: swift
# xcode_project: termina-base.xcodeproj # path to your xcodeproj folder
# xcode_scheme: termina-base
# xcode_destination: platform=macOS
osx_image: xcode10
sudo: required

script:
  ./xcbuild.sh

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_KEY
  file_glob: true
  file: "dist/Build/Products/Debug/termina"
  skip_cleanup: true
  on:
    tags: true
