language: swift
# xcode_project: termina-base.xcodeproj # path to your xcodeproj folder
# xcode_scheme: termina-base
# xcode_destination: platform=macOS
osx_image: xcode10.1

script:
  ./xcbuild.sh
  xcodebuild -scheme termina-base -project termina-base.xcodeproj -derivedDataPath dist build

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_KEY
  file_glob: true
  file: "dist/Build/Products/Debug/termina"
  skip_cleanup: true
  on:
    tags: true
