name: Build Command Line
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone source code
        uses: actions/checkout@v1
      - name: Install Apple certificates
        run: |
          echo "$ascCertificates" > certs.b64
          base64 --decode certs.b64 > Certificates.p12
          sudo security import Certificates.p12 -P "$ascCertsPassword" -k /Library/Keychains/System.keychain
        env:
          ascCertificates: ${{ secrets.ASC_CERTS }}
