name: Build Command Line
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone source code
        uses: actions/checkout@v1
      - name: Install Apple certificates
        run: |
          echo "$ascCertificates" > certs.b64
          base64 --decode certs.b64 > Certificates.p12
          security add-generic-password -a "appleseed@marquiskurt.net" -w "$ascPassword" -s "AC_PASSWORD"
          sudo security import Certificates.p12 -P "$ascCertsPassword" -k /Library/Keychains/System.keychain
        env:
          ascCertsPassword: ${{ secrets.ASC_PASSWORD }}
          ascCertificates: ${{ secrets.ASC_CERTS }}
      - name: Replace build version
        run: |
          cd base
          sed -i -e "s/let build = \"beta1\"/let build = \"build$(Build.BuildNumber)\"/g" options.swift
      - name: Run xcodebuild
        run: |
          cd base
          /usr/bin/xcodebuild -configuration Debug -workspace termina-base.xcodeproj/project.xcworkspace -scheme termina-base -destination platform=macOS build -derivedDataPath dist -forceResolvedPackageVersions | /usr/local/lib/ruby/gems/2.6.0/bin/xcpretty -r junit --no-color

